#!/usr/bin/env python3
#       Name: Frank Lewis
#       NSID: fbl773
# Student ID: 11194945
#    Lecture: 01
#   Tutorial: T01	
# Assignment: MNKY 
#   Synopsis: Calls the runTest method of all the modules when given a commandline arg.

import Problem
import Search
import informedSearch
import genTests
import sys


def testProblem():
	print ("PROBLEM")
	print ("-------")
	Problem.runTests()


def testUninformedSearch():
	print ("SEARCH")
	print ("------")
	Search.runTests()
	Search.timedTest()

def testInformedSearch():
	print ("INFORMED search")
	print ("---------------")
	informedSearch.runTests()
	informedSearch.timedTest()

def testGenerator():
	print ("GENERATOR")
	print ("---------")
	genTests.runTests()

def usage():
	msg = ("USAGE: testMNKY [-uigsp] \n"+
		"-u Displays usage \n"+
		"-i runs Informed search tester\n"+
		"-s runs uninformed search tester\n"+
		"-p runs Problem class tester\n"+
		"-g runs the test case generator teter\n")
	return msg
#main
try:
	arg1 = sys.argv[1]
	runMe = arg1.split('-')[1]
except:
	sys.exit(usage())

print ("MNKY TESTER")

if runMe is 'i':
	testInformedSearch()
elif runMe is 's':
	testUninformedSearch()
elif runMe is 'p':
	testProblem()
elif runMe is 'g':
	testGenerator()
else:
	print(usage())

